<?php
define('ZAMGWEATHER_ICON_PATH', drupal_get_path('module', 'zamgweather') .'/img/weather_icons/');

function zamgweather_get_weather() {
  $weather = array();

  //settings
  $icon = db_select('zamgweather_settings', 'zw')
      ->fields('zw', array('icon_path'))
      ->execute()
      ->fetchAssoc();

  if ($icon['icon_path']) {
    $icon_path = $icon['icon_path'];
  } else {
    $icon_path = ZAMGWEATHER_ICON_PATH;
  }
  $weather['icon_path'] = $icon_path;

  $result = db_select('zamgweather', 'zw')
      ->fields('zw')
      ->execute();
  while($record = $result->fetchAssoc()) {
    $weather[] = $record;
  }

  return $weather;
}

function zamgweather_cron() {
  zamgweather_save_xml_data();
}

function zamgweather_save_xml_data() {
  $xml = zamgweather_get_xml();

  if ($xml) {
    $days = $xml->station->prognose;

    foreach($days->children() as $day){
      $date = strtotime($day->attributes());

      foreach($day->children() as $time){
        switch ($time->attributes()) {
          case '06':
            $icon_6 = $time->param[0];
            $tmp_6 = $time->param[1];
            break;
          case '12':
            $icon_12 = $time->param[0];
            $tmp_12 = $time->param[1];
            break;
          case '18':
            $icon_18 = $time->param[0];
            $tmp_18 = $time->param[1];
            break;
          case 'tag':
            $day_icon = $time->param[0];
            $day_text = $time->param[1];
            $day_tmp_max = $time->param[2];
            $day_tmp_min = $time->param[3];
            break;
        }
      }

      db_insert('zamgweather')
      ->fields(array(
        'icon_day' => $day_icon,
        'text_day' => $day_text,
        'tmp_max_day' => $day_tmp_max,
        'tmp_min_day' => $day_tmp_min,
        'icon_6' => $icon_6,
        'tmp_6' => $tmp_6,
        'icon_12' => $icon_12,
        'tmp_12' => $tmp_12,
        'icon_18' => $icon_18,
        'tmp_18' => $tmp_18,
        'date' => $date,
        'created' => time()
      ))
      ->execute();
    }
  }
}

function zamgweather_get_xml() {
  // get zamg_settings
  $result = db_select('zamgweather_settings', 'zw')
    ->fields('zw')
    ->execute()
    ->fetchAssoc();

  if (!$result) {
    drupal_set_message(t('Please check your settings for ZAMG weather.') . ' <a href="'. base_path() .'admin/config/system/zamgweather">ZAMG weather</a>', 'warning');

  } else {
    $data = utf8_encode(file_get_contents($result['xml_path']));
    $xml = simplexml_load_string($data);
    if (is_object($xml)) {
      return $xml;
    }
  }
}
/**
 * create menu items for zamg weather
 * @return menu items
 */
function zamgweather_menu() {
  $items = array();

  $items['admin/config/system/zamgweather'] = array(
    'title' => t('ZAMG Weather Settings'),
    'description' => 'Configure ZAMG weather',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('zamgweather_admin_settings_form'),
    'access arguments' => array('administer zamg'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function zamgweather_permission() {
  return array(
    'administer zamg' => array(
      'title' => t('Administer ZAMG weather'),
      'description' => t('Settings for ZAMG weather.'),
    ),
  );
}

function zamgweather_admin_settings_form($form_state) {
  $result = db_select('zamgweather_settings', 'zw')
    ->fields('zw')
    ->execute()
    ->fetchAssoc();

  $form['settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('General settings'),
  );
  $form['settings']['xml_path'] = array(
    '#title' => t('XML Path'),
    '#type' => 'textfield',
    '#size' => 65,
    '#maxlength' => 255,
    '#required' => TRUE,
    '#default_value' => $result['xml_path'],
    '#description' => t('The path for your Weather-XML-file.'),
  );
  $form['settings']['icon_path'] = array(
    '#title' => t('Icon Path'),
    '#type' => 'textfield',
    '#size' => 65,
    '#maxlength' => 255,
    '#required' => FALSE,
    '#default_value' => $result['icon_path'],
    '#description' => t('The path for your custom icons. Leave it empty for default icons.'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#attributes' => array('class' => array('btn btn-primary')),
    '#value' => t('Save'),
  );
  return $form;
}


/**
 * save zamg weather settings
 * @param  [type] $form       [description]
 * @param  [type] $form_state [description]
 * @return [type]             [description]
 */
function zamgweather_admin_settings_form_submit($form, &$form_state) {
  $result = db_select('zamgweather_settings', 'zw')
    ->fields('zw', array('changed'))
    ->execute()
    ->fetchAssoc();

  if ($result['changed']) {
    db_update('zamgweather_settings')
      ->fields(array(
        'xml_path' => $form_state['values']['xml_path'],
        'icon_path' => $form_state['values']['icon_path'],
        'changed' => time()
      ))
      ->condition('changed', $result['changed'], '=')
      ->execute();
  } else {
    db_insert('zamgweather_settings')
      ->fields(array(
        'xml_path' => $form_state['values']['xml_path'],
        'icon_path' => $form_state['values']['icon_path'],
        'changed' => time()
      ))
      ->execute();
  }

  drupal_set_message(t('ZAMG weather settings saved.'));
}
